language: java
jdk:
- openjdk8

branches:
  only:
  - master

services:
  - mysql

before_install:
  - sudo cp $TRAVIS_BUILD_DIR/_travis/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE rezoom;'

cache:
  directories:
  - '$HOME/.m2'

script:
- mvn clean install -P ci
