# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    username: root
#    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQL55Dialect
    generate-ddl: true