# port
server:
  port: 8080

# database
spring:
  datasource:
    url: jdbc:mysql://rezoom.c67qjunwc14t.ap-northeast-2.rds.amazonaws.com:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    username: rezoom
    password: rezoom123
    driver-class-name: com.mysql.jdbc.Driver

# social oauth2
facebook:
  client:
    clientId: 490325814748030
    clientSecret: 3c4dd3da27469259bd0c72008c74bdc6
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 8fc9c81b0c9b9c851a44
    clientSecret: 7c3208fd957b33e4b686bf7fb4b6fa58e117e995
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
