# port
server:
  port: 8080

# database 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect